<a href="https://colab.research.google.com/github/akaumov/tensorflow-intro/blob/master/Introduction_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Colab.

## Introduction
Colab is Python development environment that executes in browser using google cloud.

Let's connect dependencies for backward compability. (**Run the code by clicking inside square brackets!**)

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

## Our first line of code

Let's print the "Hello world" sentence

In [23]:
print("Hello world!")

Hello world!


## Functions, iterations and loops



In [24]:
def calcXY(x,y):
  if x < 10:
    print("x < 10")
  elif x > 10 and x < 20:
    print("x > 10 and x < 20")
  else:
    print("x > 20")
  return x + y

for i in range(8, 25, 2):
  print('calcXY({}) => {}'.format(i, calcXY(i, i)))

x < 10
calcXY(8) => 16
x > 20
calcXY(10) => 20
x > 10 and x < 20
calcXY(12) => 24
x > 10 and x < 20
calcXY(14) => 28
x > 10 and x < 20
calcXY(16) => 32
x > 10 and x < 20
calcXY(18) => 36
x > 20
calcXY(20) => 40
x > 20
calcXY(22) => 44
x > 20
calcXY(24) => 48


## NumPy and lists

NumPy is the fundamental package for scientific computing in Python.

It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

If you want to learn more about NumPy you can use these links:



*   [Official Documentation](https://docs.scipy.org/doc/numpy/user/)
*   [Quick Tutorial](http://cs231n.github.io/python-numpy-tutorial/)



In [0]:
#import numpy library
import numpy as np

In [26]:
#Creating numpy arrays

a = np.array([1,2])
b = np.append(a, 3)
print("a = {}".format(a))
print("b = {}".format(b))

a = [1 2]
b = [1 2 3]


In [27]:
for i, v in enumerate(b):
  print("index = {} value = {}".format(i, v))

index = 0 value = 1
index = 1 value = 2
index = 2 value = 3


In [28]:
print("Max value = {}".format(np.max(b)))

Max value = 3


In [29]:
print("Average value = {}".format(np.average(b)))

Average value = 2.0


In [30]:
print("Max index = {}".format(np.argmax(b)))

Max index = 2


In [31]:
print("Type of b = {}", type(b))

Type of b = {} <class 'numpy.ndarray'>


In [32]:
rnd = np.random.rand(3, 3,3, 3)
print(rnd)

[[[[0.19539305 0.28131767 0.12380207]
   [0.0691764  0.31912212 0.54538568]
   [0.94465105 0.78838315 0.70148933]]

  [[0.7235741  0.02585023 0.40730228]
   [0.32342419 0.77998236 0.28793912]
   [0.02048706 0.65649224 0.65949628]]

  [[0.85402365 0.50585138 0.68941116]
   [0.16884251 0.67689413 0.48449254]
   [0.84411363 0.44293161 0.16328479]]]


 [[[0.33123324 0.72132401 0.48256743]
   [0.10567121 0.50267561 0.03090486]
   [0.70455901 0.29192943 0.26784752]]

  [[0.76131183 0.24529287 0.83522958]
   [0.23573758 0.70620719 0.19842737]
   [0.00904972 0.71890765 0.49673119]]

  [[0.32103952 0.09783389 0.60106753]
   [0.00949495 0.09480089 0.01616679]
   [0.11037419 0.860412   0.13832613]]]


 [[[0.76750276 0.70578991 0.93887403]
   [0.15240548 0.52446046 0.24979387]
   [0.95560913 0.66878385 0.62991623]]

  [[0.03010918 0.60747582 0.7426905 ]
   [0.46492019 0.94308128 0.63990563]
   [0.19290089 0.36214437 0.40112098]]

  [[0.08900091 0.94092114 0.85164447]
   [0.0440474  0.39444374 0.51

In [33]:
print("Shape of a = {}".format(a.shape))

Shape of a = (2,)


In [34]:
print("Shape of rnd = {}".format(rnd.shape))

Shape of rnd = (3, 3, 3, 3)


## Colab Specifics

Because all code executes in the virtual machine you can run linux commands.

Let's print current working directory by executing the "pwd" command.

In [35]:
!pwd

/content


In [36]:
!ls -l

total 4
drwxr-xr-x 1 root root 4096 Jun 18 16:14 sample_data


In [37]:
!cd /
!ls -la

total 16
drwxr-xr-x 1 root root 4096 Jun 18 16:14 .
drwxr-xr-x 1 root root 4096 Jun 28 09:15 ..
drwxr-xr-x 1 root root 4096 Jun 18 16:14 .config
drwxr-xr-x 1 root root 4096 Jun 18 16:14 sample_data


Let's print the "sample_data" directory content

In [38]:
!ls -la ./sample_data

total 55512
drwxr-xr-x 1 root root     4096 Jun 18 16:14 .
drwxr-xr-x 1 root root     4096 Jun 18 16:14 ..
-r-xr-xr-x 1 root root     1697 Jan  1  2000 anscombe.json
-rw-r--r-- 1 root root   301141 Jun 18 16:14 california_housing_test.csv
-rw-r--r-- 1 root root  1706430 Jun 18 16:14 california_housing_train.csv
-rw-r--r-- 1 root root 18289443 Jun 18 16:14 mnist_test.csv
-rw-r--r-- 1 root root 36523880 Jun 18 16:14 mnist_train_small.csv
-r-xr-xr-x 1 root root      930 Jan  1  2000 README.md


Let's print the content one of the files

In [39]:
!ls -la ./sample_data
!cat ./sample_data/anscombe.json

total 55512
drwxr-xr-x 1 root root     4096 Jun 18 16:14 .
drwxr-xr-x 1 root root     4096 Jun 18 16:14 ..
-r-xr-xr-x 1 root root     1697 Jan  1  2000 anscombe.json
-rw-r--r-- 1 root root   301141 Jun 18 16:14 california_housing_test.csv
-rw-r--r-- 1 root root  1706430 Jun 18 16:14 california_housing_train.csv
-rw-r--r-- 1 root root 18289443 Jun 18 16:14 mnist_test.csv
-rw-r--r-- 1 root root 36523880 Jun 18 16:14 mnist_train_small.csv
-r-xr-xr-x 1 root root      930 Jan  1  2000 README.md
[
  {"Series":"I", "X":10.0, "Y":8.04},
  {"Series":"I", "X":8.0, "Y":6.95},
  {"Series":"I", "X":13.0, "Y":7.58},
  {"Series":"I", "X":9.0, "Y":8.81},
  {"Series":"I", "X":11.0, "Y":8.33},
  {"Series":"I", "X":14.0, "Y":9.96},
  {"Series":"I", "X":6.0, "Y":7.24},
  {"Series":"I", "X":4.0, "Y":4.26},
  {"Series":"I", "X":12.0, "Y":10.84},
  {"Series":"I", "X":7.0, "Y":4.81},
  {"Series":"I", "X":5.0, "Y":5.68},

  {"Series":"II", "X":10.0, "Y":9.14},
  {"Series":"II", "X":8.0, "Y":8.14},
  {"Series":